modules :
  - psfws.simulate_atm_psf


eval_variables:
  cboresight:
    type : RADec
    ra : {type : Degrees, theta: {type : OpsimData, field: fieldRa}}
    dec : {type : Degrees, theta: {type : OpsimData, field: fieldDec}}

  aazimuth:
    type : Degrees
    theta : {type : OpsimData, field: azimuth}

  aaltitude: 
    type : Degrees
    theta : {type : OpsimData, field: altitude}


input :
  atm_psf :
    screen_size : 800
    band : { type: OpsimData, field: band }
    alt : "$altitude"
    az : "$azimuth"
    boresight : "$boresight"
    save_file:
      type: FormattedStr
      format: atm_psf_files/atm_psf_%08d-%1d-%s.pkl
      items:
          - { type: OpsimData, field: observationId }
          - { type: OpsimData, field: snap }
          - { type: OpsimData, field: band }


psf :
  type : Convolution
  items : 
    - type : ImsimAtmosphericPSF

    - type : Gaussian
      sigma : 0.35


image : 
  pixel_scale : 0.2
  size : 50
  draw_method : 'phot'
  n_photons : 1000000
  random_seed : 192476