modules :
  - psfws_atm_psf


# comment out the input block if using simpler non-imsim version 
input :
  atm_psf :
    screen_size : 800
    save_file:
      type: FormattedStr
      format: atm_psf_files/atm_psf_%08d-%1d-%s.pkl
      items:
          - { type: OpsimData, field: observationId }
          - { type: OpsimData, field: snap }
          - { type: OpsimData, field: band }

psf :
  type : Convolution
  items : 
    - type : ImsimAtmosphericPSF

    # use this for simpler sims w/o loading module
    # - type : AtmosphericPSF
      # screen_size : 800
      # band : 'i'
      # alt : 60
      # az : 270
      # field_x : 20
      # field_y : 30 

    - type : Gaussian
      sigma : 0.35

image : 
  pixel_scale : 0.2
  size : 50
  draw_method : 'phot'
  n_photons : 1000000
  random_seed : 192476